import React from 'react';
import { 
  LayoutDashboard, 
  Briefcase, 
  Film, 
  BarChart2, 
  Users, 
  Zap, 
  CreditCard, 
  Bell, 
  Search, 
  Plus, 
  Image as ImageIcon, 
  Send, 
  Share2, 
  Settings, 
  ChevronRight, 
  ChevronLeft, 
  Clock, 
  DollarSign, 
  UserCheck, 
  Layers, 
  Smile, 
  Box, 
  Wand2, 
  Flame, 
  Globe, 
  BookOpen, 
  Award, 
  ArrowUp, 
  Filter, 
  ListFilter, 
  MessageCircle, 
  CalendarDays, 
  X, 
  Archive, 
  Star, 
  ThumbsUp, 
  Activity, 
  CheckCircle, 
  XCircle, 
  Folder, 
  Upload, 
  Trash2, 
  MoreHorizontal, 
  ImagePlus, 
  Video, 
  Scissors, 
  ShoppingCart, 
  Youtube, 
  Instagram, 
  Facebook, 
  Twitter, 
  MessageSquare, 
  LogOut, 
  User, 
  Smartphone, 
  QrCode, 
  Wallet, 
  ShieldCheck, 
  Check, 
  Play, 
  Lock, 
  Unlock, 
  Newspaper, 
  Mic,
  AlertTriangle,
  Info,
  RotateCcw,
  Download,
  Save,
  ChevronDown,
  Maximize2,
  MapPin,
  Gift,
  Music,
  Type
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Tasks: Briefcase,
  Briefcase: Briefcase,
  Studio: Film,
  Film: Film,
  Analytics: BarChart2,
  Community: Users,
  Users: Users,
  Spark: Zap,
  Credits: CreditCard,
  CreditCard: CreditCard,
  Notification: Bell,
  Search: Search,
  Plus: Plus,
  Image: ImageIcon,
  Send: Send,
  Share: Share2,
  Settings: Settings,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronDown: ChevronDown,
  Clock: Clock,
  Price: DollarSign,
  Accepted: UserCheck,
  Layers: Layers,
  Character: Smile,
  Props: Box,
  // Fix: Expose Box directly
  Box: Box,
  Magic: Wand2,
  Wand2: Wand2,
  Hot: Flame,
  Flame: Flame,
  Global: Globe,
  Course: BookOpen,
  BookOpen: BookOpen,
  Award: Award,
  ArrowUp: ArrowUp,
  Filter: Filter,
  ListFilter: ListFilter,
  Wechat: MessageCircle,
  Yen: DollarSign, 
  Calendar: CalendarDays,
  Close: X,
  X: X,
  Archive: Archive,
  Star: Star,
  ThumbsUp: ThumbsUp,
  Activity: Activity,
  CheckCircle: CheckCircle,
  XCircle: XCircle,
  Folder: Folder,
  Upload: Upload,
  Trash: Trash2,
  More: MoreHorizontal,
  ImagePlus: ImagePlus,
  Video: Video,
  Cut: Scissors,
  Cart: ShoppingCart,
  Youtube: Youtube,
  Instagram: Instagram,
  Facebook: Facebook,
  Twitter: Twitter,
  Telegram: MessageSquare,
  LogOut: LogOut,
  User: User,
  Smartphone: Smartphone,
  QrCode: QrCode,
  Wallet: Wallet,
  Crown: Award, // Using Award as Crown substitute or explicit Crown if available in newer lucide
  ShieldCheck: ShieldCheck,
  Check: Check,
  Play: Play,
  Lock: Lock,
  Unlock: Unlock,
  News: Newspaper,
  Mic: Mic,
  AlertTriangle: AlertTriangle,
  Info: Info,
  RotateCcw: RotateCcw,
  Download: Download,
  Save: Save,
  Maximize: Maximize2,
  MapPin: MapPin,
  Gift: Gift,
  Music: Music,
  Type: Type,
  Zap: Zap
};